name: notion-linux
title: Notion for linux.
contact: xinorprime@gmail.com
issues: 
website: 
icon: resources/icon.png
license: MIT
summary: Notion for linux.
description: A simple application that offers notion web application with electron.
version: '1.0'

apps:
  notionlinux:
    command: notion-linux